let stockProductos = [
  {
    id: 1,
    nombre: "Queso Azul",
    tipo: "Lacteos",
    cantidad: 1,
    desc: "Unos de los mejores quesos azules de la zona",
    precio: 1200,
    talle: "L",
    img: "../imagenes/images.jpeg",
  },
  {
    id: 2,
    nombre: "Queso Azul",
    tipo: "Lacteos",
    cantidad: 1,
    desc: "Unos de los mejores quesos azules de la zona",
    precio: 1100,
    talle: "L",
    img: "../imagenes/images.jpeg",
  },
  {
    id: 3,
    nombre: "Queso Azul",
    tipo: "Lacteos",
    cantidad: 1,
    desc: "Unos de los mejores quesos azules de la zona",
    precio: 1200,
    talle: "M",
    img: "../imagenes/images.jpeg",
  },
  {
    id: 4,
    nombre: "Queso Azul",
    tipo: "Lacteos",
    cantidad: 1,
    desc: "Unos de los mejores quesos azules de la zona",
    precio: 1400,
    talle: "M",
    img: "../imagenes/images.jpeg",
  },
  {
    id: 5,
    nombre: "Queso Azul",
    tipo: "Lacteos",
    cantidad: 1,
    desc: "Unos de los mejores quesos azules de la zona",
    precio: 1200,
    talle: "S",
    img: "../imagenes/images.jpeg",
  },
];
